plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.guava:guava:30.1-jre'
    
    constraints {
        implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.6.0'
    }
}

allprojects { project -> 
    dependencyLocking {
        lockAllConfigurations()
    }
    task resolveAndLockAll {
        doFirst {
            assert gradle.startParameter.writeDependencyLocks
        }
        doLast {
            configurations.findAll {
                it.canBeResolved
            }.each { it.resolve() }
        }
    }
}

task run(type: JavaExec) {
    main = 'com.example.Main'
    classpath = sourceSets.main.runtimeClasspath
}
